// Code generated by go-swagger; DO NOT EDIT.

package form

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ogaravito-yofio/tech-challenge-v2/models"
)

// AddPeopleCreatedCode is the HTTP code returned for type AddPeopleCreated
const AddPeopleCreatedCode int = 201

/*AddPeopleCreated People register was successfully created in database

swagger:response addPeopleCreated
*/
type AddPeopleCreated struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewAddPeopleCreated creates AddPeopleCreated with default headers values
func NewAddPeopleCreated() *AddPeopleCreated {

	return &AddPeopleCreated{}
}

// WithPayload adds the payload to the add people created response
func (o *AddPeopleCreated) WithPayload(payload *models.APIResponse) *AddPeopleCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add people created response
func (o *AddPeopleCreated) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddPeopleCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddPeopleBadRequestCode is the HTTP code returned for type AddPeopleBadRequest
const AddPeopleBadRequestCode int = 400

/*AddPeopleBadRequest Invalid input.

swagger:response addPeopleBadRequest
*/
type AddPeopleBadRequest struct {
}

// NewAddPeopleBadRequest creates AddPeopleBadRequest with default headers values
func NewAddPeopleBadRequest() *AddPeopleBadRequest {

	return &AddPeopleBadRequest{}
}

// WriteResponse to the client
func (o *AddPeopleBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
