// Code generated by go-swagger; DO NOT EDIT.

// Package tech_challenge_v2 YoFio Recruitment - Tech Challenge
//
//  Terms Of Service:
//    http://swagger.io/terms/
//  Schemes:
//    http
//    https
//  Host: petstore.swagger.io
//  BasePath: /
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: <ogaravito@yofio.co>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package tech_challenge_v2
